### ISSUE TITLE
Players can Ace interact to get into vehicles (Bypasses our vehicle restriction script)

### ISSUE THREAD

**Issue by VexA3** [BojanOnTheInternet/7Cav_FullSpectrum_V4.Malden#54] opened 2019-02-07 08:29 UTC

**Comment by BojanOnTheInternet** [comment] 2019-02-08 21:45
@Robot-Panda15 I believe the issue is ACE Quick Mount. Please disable it as a server setting. Tested locally to work. 

Closing.

**Closed by BojanOnTheInternet** 2019-02-08 21:45 UTC
Labels: urgent
